const LEVELS = [
  { id: 1, title: "小动物找朋友", icon: "🐱", pairs: 6, columns: 4, pool: ["🐱", "🐶", "🐰", "🐘", "🦊", "🐷"] },
  { id: 2, title: "佩奇的泥坑派对", icon: "🐷", pairs: 8, columns: 4, pool: ["🐷", "🐽", "🌧️", "☂️", "👢", "💦", "🌈", "🍪"] },
  { id: 3, title: "汪汪队小小救援", icon: "🚒", pairs: 9, columns: 6, pool: ["🐶", "🚒", "🚓", "🚑", "🚁", "🦴", "🧯", "📣", "🛟"] },
  { id: 4, title: "皮普波西花园会", icon: "🌷", pairs: 12, columns: 6, pool: ["🐰", "🐭", "🌷", "🌼", "🦋", "🐞", "🌳", "🌱", "🪴", "🍓", "🧺", "🎨"] },
  { id: 5, title: "森林露营夜", icon: "⛺", pairs: 15, columns: 6, pool: ["🦊", "🐻", "🐿️", "🦉", "⛺", "🔥", "🌙", "⭐", "🍄", "🌲", "🍃", "🥪", "🧃", "🧭", "🔦"] },
  { id: 6, title: "海底寻宝", icon: "🐠", pairs: 18, columns: 6, pool: ["🐠", "🐟", "🐳", "🦈", "🐙", "🦑", "🐬", "🦀", "🐡", "🐚", "🦐", "🦞", "🪸", "⚓", "🛟", "💎", "🔱", "🫧"] },
  { id: 7, title: "恐龙大冒险", icon: "🦖", pairs: 20, columns: 8, pool: ["🦖", "🦕", "🥚", "🌋", "🦴", "🌴", "🌿", "🪨", "☀️", "🌈", "🐊", "🦎", "🐢", "🐍", "🐾", "🦟", "🍂", "🌾", "🏞️", "⛰️"] },
  { id: 8, title: "太空探险队", icon: "🚀", pairs: 24, columns: 8, pool: ["🚀", "🛸", "🪐", "🌍", "🌕", "⭐", "☄️", "👩‍🚀", "👨‍🚀", "🤖", "🛰️", "🔭", "🌌", "🌎", "🧑‍🚀", "📡", "🔋", "💫", "🌠", "☀️", "🌑", "🟣", "🔵", "🟡"] },
  { id: 9, title: "梦幻嘉年华", icon: "🎡", pairs: 28, columns: 8, pool: ["🎡", "🎠", "🎢", "🎪", "🎈", "🎉", "🎁", "🍭", "🍿", "🍦", "🧁", "🍩", "🎵", "🎺", "🥁", "🎨", "🪄", "👑", "🦄", "🐉", "🌟", "💖", "🧸", "🎲", "🪀", "🛼", "🎯", "🎳"] },
];
const state = { level: null, board: [], selected: null, remaining: 0, sound: true, unlocked: Number(localStorage.getItem("littleLinkUnlocked") || 1) };
const el = { levelScreen: document.getElementById("levelScreen"), gameScreen: document.getElementById("gameScreen"), levelList: document.getElementById("levelList"), board: document.getElementById("board"), gameTitle: document.getElementById("gameTitle"), levelBadge: document.getElementById("levelBadge"), progressBar: document.getElementById("progressBar"), matchCount: document.getElementById("matchCount"), hint: document.getElementById("gameHint"), overlay: document.getElementById("completeOverlay"), completeText: document.getElementById("completeText"), next: document.getElementById("nextButton"), sound: document.getElementById("soundButton") };
let audioContext;
function shuffle(items) { const copy = [...items]; for (let i = copy.length - 1; i > 0; i -= 1) { const j = Math.floor(Math.random() * (i + 1)); [copy[i], copy[j]] = [copy[j], copy[i]]; } return copy; }
function renderLevels() { el.levelList.innerHTML = ""; LEVELS.forEach((level) => { const unlocked = level.id <= state.unlocked; const card = document.createElement("button"); card.className = "level-card"; card.type = "button"; card.disabled = !unlocked; card.innerHTML = `<span class="level-number">第 ${level.id} 关</span><span class="level-icon" aria-hidden="true">${level.icon}</span><strong>${level.title}</strong><small>${level.pairs} 对朋友</small>${unlocked ? "" : '<span class="lock" aria-label="未解锁">&#128274;</span>'}`; if (unlocked) card.addEventListener("click", () => startLevel(level.id)); el.levelList.appendChild(card); }); }
function startLevel(id) { state.level = LEVELS.find((level) => level.id === id); state.selected = null; state.remaining = state.level.pairs; const symbols = state.level.pool.slice(0, state.level.pairs); state.board = shuffle(symbols.flatMap((symbol, index) => [{ symbol, id: `${index}-a`, removed: false }, { symbol, id: `${index}-b`, removed: false }])); el.levelScreen.classList.add("is-hidden"); el.gameScreen.classList.remove("is-hidden"); el.overlay.classList.add("is-hidden"); el.gameTitle.textContent = state.level.title; el.levelBadge.textContent = `第 ${state.level.id} 关`; el.board.style.setProperty("--columns", state.level.columns); updateGameView(); }
function updateGameView() { const done = state.level.pairs - state.remaining; el.progressBar.style.width = `${(done / state.level.pairs) * 100}%`; el.matchCount.textContent = state.remaining ? `还剩 ${state.remaining} 对` : "全部找到了"; renderBoard(); }
function renderBoard() { el.board.innerHTML = ""; state.board.forEach((tile, index) => { const button = document.createElement("button"); button.type = "button"; button.className = "tile"; button.dataset.index = index; if (tile.removed) { button.classList.add("empty"); button.disabled = true; } else { button.innerHTML = tile.symbol; button.setAttribute("aria-label", "图案"); if (state.selected === index) button.classList.add("selected"); button.addEventListener("click", () => selectTile(index)); } el.board.appendChild(button); }); }
function selectTile(index) { if (state.board[index].removed) return; playTone(460, .05); if (state.selected === null) { state.selected = index; el.hint.textContent = "再找一个一样的图案"; renderBoard(); return; } if (state.selected === index) { state.selected = null; el.hint.textContent = "点两个一样的图案试一试"; renderBoard(); return; } const first = state.selected; const same = state.board[first].symbol === state.board[index].symbol; if (same && canConnect(first, index)) { state.board[first].removed = true; state.board[index].removed = true; state.selected = null; state.remaining -= 1; el.hint.textContent = state.remaining ? "找到啦！再找一对。" : "全部找到啦！"; playSuccess(); if (state.remaining) ensurePlayable(); updateGameView(); if (!state.remaining) window.setTimeout(completeLevel, 480); } else { state.selected = index; el.hint.textContent = same ? "这两个朋友现在还不能见面，试试别的一对。" : "不是同一个朋友，换一个试试。"; playTone(250, .1); renderBoard(); } }
// Search paths with zero to two turns; the padded grid permits routes around board edges.
function canConnect(firstIndex, secondIndex) { const columns = state.level.columns; const rows = state.board.length / columns; const grid = Array.from({ length: rows + 2 }, () => Array(columns + 2).fill(false)); state.board.forEach((tile, index) => { if (!tile.removed) grid[Math.floor(index / columns) + 1][(index % columns) + 1] = true; }); const start = [Math.floor(firstIndex / columns) + 1, (firstIndex % columns) + 1]; const end = [Math.floor(secondIndex / columns) + 1, (secondIndex % columns) + 1]; grid[start[0]][start[1]] = false; grid[end[0]][end[1]] = false; const queue = [{ row: start[0], col: start[1], direction: -1, turns: 0 }]; const visited = Array.from({ length: rows + 2 }, () => Array.from({ length: columns + 2 }, () => Array(4).fill(3))); const directions = [[-1, 0], [1, 0], [0, -1], [0, 1]]; while (queue.length) { const current = queue.shift(); for (let direction = 0; direction < 4; direction += 1) { const turns = current.direction === -1 || current.direction === direction ? current.turns : current.turns + 1; if (turns > 2) continue; const row = current.row + directions[direction][0]; const col = current.col + directions[direction][1]; if (row < 0 || row >= rows + 2 || col < 0 || col >= columns + 2 || grid[row][col]) continue; if (row === end[0] && col === end[1]) return true; if (visited[row][col][direction] <= turns) continue; visited[row][col][direction] = turns; queue.push({ row, col, direction, turns }); } } return false; }
function findAvailablePair() { for (let first = 0; first < state.board.length; first += 1) { if (state.board[first].removed) continue; for (let second = first + 1; second < state.board.length; second += 1) if (!state.board[second].removed && state.board[first].symbol === state.board[second].symbol && canConnect(first, second)) return [first, second]; } return null; }
function ensurePlayable() { if (findAvailablePair()) return; const positions = state.board.map((tile, index) => tile.removed ? -1 : index).filter((index) => index >= 0); const tiles = positions.map((index) => state.board[index]); for (let attempt = 0; attempt < 80; attempt += 1) { const shuffled = shuffle(tiles); positions.forEach((index, tileIndex) => { state.board[index] = shuffled[tileIndex]; }); if (findAvailablePair()) { el.hint.textContent = "图案换了新位置，继续找朋友吧。"; return; } } }
function showHint() { const pair = findAvailablePair(); if (!pair) { el.hint.textContent = "换一换图案，再试一次。"; return; } state.selected = null; renderBoard(); pair.forEach((index) => el.board.querySelector(`[data-index="${index}"]`).classList.add("hint")); el.hint.textContent = "这两个朋友可以碰面。"; playTone(650, .12); }
function completeLevel() { if (state.level.id < LEVELS.length) { state.unlocked = Math.max(state.unlocked, state.level.id + 1); localStorage.setItem("littleLinkUnlocked", state.unlocked); el.next.textContent = "下一关"; } else el.next.textContent = "再玩一次"; el.completeText.textContent = state.level.id === LEVELS.length ? "三关全都完成了！" : "你帮所有朋友找到了伙伴。"; el.overlay.classList.remove("is-hidden"); renderLevels(); }
function goHome() { state.selected = null; el.overlay.classList.add("is-hidden"); el.gameScreen.classList.add("is-hidden"); el.levelScreen.classList.remove("is-hidden"); renderLevels(); }
function playTone(frequency, duration) { if (!state.sound || !(window.AudioContext || window.webkitAudioContext)) return; const Context = window.AudioContext || window.webkitAudioContext; if (!audioContext || audioContext.state === "closed") audioContext = new Context(); if (audioContext.state === "suspended") audioContext.resume().catch(() => {}); const oscillator = audioContext.createOscillator(); const gain = audioContext.createGain(); oscillator.type = "sine"; oscillator.frequency.value = frequency; gain.gain.setValueAtTime(.075, audioContext.currentTime); gain.gain.exponentialRampToValueAtTime(.001, audioContext.currentTime + duration); oscillator.connect(gain).connect(audioContext.destination); oscillator.start(audioContext.currentTime); oscillator.stop(audioContext.currentTime + duration); }
function playSuccess() { playTone(660, .09); window.setTimeout(() => playTone(880, .14), 95); }
document.getElementById("hintButton").addEventListener("click", showHint); document.getElementById("restartButton").addEventListener("click", () => startLevel(state.level.id)); document.getElementById("homeButton").addEventListener("click", goHome); document.getElementById("chooseLevelButton").addEventListener("click", goHome); el.next.addEventListener("click", () => startLevel(state.level.id === LEVELS.length ? 1 : state.level.id + 1)); el.sound.addEventListener("click", () => { state.sound = !state.sound; el.sound.innerHTML = `<span aria-hidden="true">${state.sound ? "&#128266;" : "&#128263;"}</span>`; el.sound.setAttribute("aria-label", state.sound ? "关闭声音" : "打开声音"); });
renderLevels(); if ("serviceWorker" in navigator) window.addEventListener("load", () => navigator.serviceWorker.register("sw.js"));
